# Generated by Django 2.2.6 on 2020-02-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='depatments_in_organization',
            field=models.CharField(choices=[('dept1', 'depatment1'), ('dept2', 'department2')], default='dept1', max_length=10),
        ),
    ]
