# Generated by Django 2.2.6 on 2020-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_profile_depatments_in_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='depatments_in_organization',
            field=models.CharField(choices=[('dept1', 'department1'), ('dept2', 'department2')], default='dept1', max_length=10),
        ),
    ]
