# Generated by Django 2.2.6 on 2020-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskassign', '0002_tasks_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='assined_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.OneToOneField(on_delete='CASCADE', to='taskassign.tasks')),
            ],
        ),
    ]
