# Generated by Django 2.2.6 on 2020-02-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskassign', '0003_assined_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assined_task',
            name='task_id',
        ),
        migrations.AddField(
            model_name='assined_task',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assined_task',
            name='emp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assined_task',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='assined_task',
            name='task',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
